baseURL = "https://til.tlgs.dev"
title = "til.tlgs"

capitalizeListTitles = false
disableKinds = ["sitemap", "RSS"]

markup.highlight.style = "pygments"
markup.goldmark.extensions.typographer = false

[taxonomies]
  tag = "tags"

[frontmatter]
  date = [":filename", ":default"]
